<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\openkogama-photon\openkogama-photon.csproj" />
    <ProjectReference Include="api\openkogama-api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="api\**;examples\**;browser\**" />
    <None Remove="api\**;examples\**;browser\**" />
    <Content Include="data\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>OpenKogama</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
