<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\api\openkogama-api.csproj" Private="false" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>welcome</AssemblyName>
    <RootNamespace>Welcome</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <Target Name="CopyToServer" AfterTargets="Build">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="..\..\bin\$(Configuration)\net10.0\plugins" />
  </Target>

</Project>
