namespace OpenKogama.Kogama;

public enum DBQueryKey : byte
{
    ProfileID = 0,
    ItemID = 9,
    ItemName = 10,
    ItemData = 11,
    ItemTypeID = 15,
    SlotIndex = 22,
    FriendProfileID = 26,
    FriendStatus = 28,
    MaterialName = 51,
    MaterialDescription = 52,
    MaterialPath = 53,
    MaterialSound = 54,
    AvatarModifierPackageType = 55,
    MaterialAnimatorTypeName = 56,
    MaterialUnlockPrice = 57,
    MaterialUnlockPriceSilver = 58,
    MaterialUnlocked = 59,
    StreamingAssetID = 62,
    StreamingAssetTypeID = 64,
    StreamingAssetCategoryID = 66,
    StreamingAssetName = 67,
    StreamingAssetDescription = 68,
    StreamingAssetURL = 69,
    StreamingAssetInventoryID = 73,
    PriceGold = 76,
    PriceSilver = 77,
    RentPriceSilver = 78,
    RentPriceGold = 79,
    RentExpireSeconds = 80,
    IsRented = 81,
    PurchaseTimeTicks = 83,
    KogamaData = 92,
    PositionIndex = 101,
    Resellable = 104,
    AuthorProfileID = 106,
    ItemDescription = 107,
    ShopInventoryID = 108,
    Deleted = 109,
    OriginalItemID = 110,
    MaterialPhysicalProperties = 115,
    ItemCategoryID = 116,
}

