namespace OpenKogama.Kogama;

public enum EventCode : byte
{
    UnregisterWorldObject = 1,
    UpdateWorldObject = 2,
    UpdateWorldObjectData = 3,
    UpdateWorldObjectDataPartial = 4,
    RemoveWorldObjectDataPartial = 5,
    TransferOwnership = 6,
    UnregisterPrototype = 9,
    UpdatePrototype = 10,
    AddLink = 13,
    RemoveLink = 14,
    TriggerBoxStayBegin = 21,
    TriggerBoxStayEnd = 22,
    WoUniquePrototype = 27,
    UpdateWorldObjectRunTimeData = 31,
    PickupItemStateChange = 32,
    UpdateLineOfFire = 33,
    PostGameMsg = 36,
    WorldObjectRPCEvent = 34,
    SetTeam = 37,
    AddObjectLink = 38,
    RemoveObjectLink = 39,
    CloneWorldObjectTree = 43,
    GetGameBatch = 44,
    GameQueryReady = 45,
    AttachWorldObjectToSeat = 51,
    DetachWorldObjectFromVehicle = 52,
    SpawnVehicleWithDriver = 53,
    ResetTerrain = 56,
    Join = 255,
}
