namespace OpenKogama.Kogama;

public enum OperationCode : byte
{
    SetActorReady = 0,
    DBQuery = 1,
    LargeDBQuery = 2,
    GetNextResultSet = 3,
    UnregisterWorldObject = 5,
    UpdateWorldObject = 6,
    UpdateWorldObjectData = 7,
    UpdateWorldObjectDataPartial = 8,
    RemoveWorldObjectDataPartial = 9,
    TransferOwnership = 11,
    UpdatePrototype = 12,
    AddLink = 14,
    RemoveLink = 15,
    RequestFriends = 20,
    TriggerBoxEnter = 25,
    TriggerBoxExit = 26,
    RequestWoUniquePrototype = 31,
    UpdateWorldObjectRunTimeData = 35,
    UpdateLineOfFire = 37,
    WorldObjectRPCOperation = 38,
    PostGameMsg = 40,
    SetTeam = 41,
    AddObjectLink = 42,
    RemoveObjectLink = 43,
    CloneWorldObjectTree = 45,
    RequestMaterials = 46,
    GetNextGameBatch = 51,
    RequestStreamingAssetList = 52,
    RequestStreamingAssetInventory = 53,
    RequestBuiltInItem = 55,
    AddItemToWorld = 56,
    GetCreditStatus = 62,
    GetBuiltInItemBusinessData = 63,
    CreateGameSnapshot = 69,
    AttachWorldObjectToSeat = 70,
    DetachWorldObjectFromVehicle = 71,
    SpawnVehicleWithDriver = 72,
    ResetTerrain = 76,
    GetDBTimeTicks = 64,
    Join = 255,
}
