namespace OpenKogama.Kogama;

public enum ParameterKey : byte
{
    DBQuery = 0,
    DBQueryOutData = 1,
    Username = 9,
    ProfileID = 11,
    UserList = 13,
    WorldObjectID = 20,
    PlanetOwnershipType = 14,
    Friends = 49,
    GameStateType = 63,
    GameStateDuration = 64,
    GameStateStartTime = 65,
    GameStateReason = 66,
    IsGamePublished = 81,
    TeamID = 89,
    TeamList = 90,
    MaterialList = 93,
    QueryId = 99,
    QueryDataLeft = 100,
    AssetBundleRootUrl = 104,
    StreamingAssetList = 108,
    StreamingAssetInventory = 109,
    GoldAmount = 130,
    SilverAmount = 131,
    DBTimeTicks = 133,
    QueryType = 134,
    RegionCode = 155,
    FineGrainedTerrainPrototypeID = 157,
    GameStatCounterData = 159,
    ClientSettingFlags = 169,
    Level = 170,
    GameType = 171,
    APIUrl = 175,
    LevelingSilentMode = 176,
    Format = 178,
    GameCoinBoosterLeft = 180,
    MarketPlaceLevel = 182,
    Prices = 183,
    PublishLevel = 185,
    Data = 245,
    ActorNr = 254,
}
